# Generated by Django 3.1.4 on 2020-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_shop_name', models.CharField(max_length=128, verbose_name='店铺名称')),
                ('c_address', models.CharField(max_length=256, verbose_name='店铺位置')),
                ('c_location', models.CharField(max_length=256, verbose_name='店铺位置')),
                ('i_type', models.IntegerField(verbose_name='店铺类型')),
                ('c_pay_qr_code', models.CharField(max_length=512)),
                ('c_description', models.CharField(max_length=1024, verbose_name='店铺描述')),
                ('c_images', models.CharField(max_length=1024, verbose_name='店铺图片')),
                ('d_create_time', models.DateTimeField(verbose_name='店铺创建时间')),
            ],
        ),
    ]
